(defun insert-time ()
  (interactive)
  (insert (format-time-string "%Y-%m-%d-%R")))

(defun journal () 
  (interactive) 
  (find-file "~/journel")
  (end-of-buffer)
  (insert "\n")
  (insert "**  ")
  (insert-time)
  (insert "  **")
  (insert "\n    ")
)